language: objective-c
osx_image: xcode7.2
env:
    - TEST_CONFIG="RELEASE"
    - TEST_CONFIG="PODS"

before_install: true
install: true
script: 
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then script/cibuild SwiftCheck SwiftCheck-iOS SwiftCheck-tvOS ; fi
    - if [[ "$TEST_CONFIG" == "PODS" ]]; then pod lib lint; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
